import math
a = int(input("Enter a:"))
b = int(input("Enter b:"))
c = int(input("Enter c:"))
cos_alpha = (a**2+c**2+b**2)/2*(a*c)
print("Cos alpha is:", cos_alpha)
cos_beta = (a**2+c**2+b**2)/2*(a*b)
print("Cos beta is:", cos_beta)
cos_gama = (a**2+c**2+b**2)/2*(c*b)
print("Cos gama is:", cos_beta)